eCommWeb/Controllers/CartController.cs
using eCommWeb.Data;
using eCommWeb.Helpers;
using eCommWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using MimeKit;
using MailKit.Net.Smtp;
using System.Net;
using MailKit.Security;
using MimeKit.Text;
using System.Globalization;


//using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace eCommWeb.Controllers
{
    [Authorize]
    [Route("cart")]
    [ApiController]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        //private readonly IdentityDbContext _identityDb;

        public CartController(ApplicationDbContext db)
        {
            _db = db;

        }

        [Route("index")]
        [HttpGet]
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            if (cart != null)
            {
                ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Product");
            }

        }

        [Route("buy/{id}")]
        [HttpGet]
        public IActionResult Buy(int id)
        {
            Product productModel = new Product();
            var res = _db.Product.FirstOrDefault(x => x.Id == id);
            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Product = res, Quantity = 1 });

                

                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Product = res, Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        [Route("remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

        [Route("addToCart")]
        [HttpGet]
        public IActionResult AddToCart(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            var bodyBuilder = new BodyBuilder();

            foreach (var res in cart)
            {
                Item orderDetail = new()
                {
                    ProductId = res.Product.Id,
                    Quantity = res.Quantity,
                    SubTotal = (res.Quantity * Convert.ToInt32(res.Product.Price)),
                    PurchaseDate = DateTime.Now,
                    IdentityUserName = HttpContext.User.Identity.Name,
                };

                bodyBuilder.HtmlBody += @"<tr>
				                                    <td>" + res.Product.Name + @"</td>
                                                    <td>" + res.Product.Price?.ToString("C", CultureInfo.CurrentCulture) + @"</td>
				                                    <td style=text-align:center>" + res.Quantity + @"</td>
				                                    <td>" + (res.Quantity * Convert.ToInt32(res.Product.Price)).ToString("C", CultureInfo.CurrentCulture) + @"</td>
				                                    <td>" + DateTime.Now.ToString("yyyy-MM-dd") + @"</td>
		                                 </tr>";


                _db.Item.Add(orderDetail);
                _db.SaveChanges();
            }

            var message = new MimeMessage();
            message.From.Add(MailboxAddress.Parse("dangelo19@ethereal.email"));
            message.To.Add(MailboxAddress.Parse(HttpContext.User.Identity.Name));
            //message.To.Add(MailboxAddress.Parse(HttpContext.User.Identity.Name));
            message.Subject = "Test Email Subject";


            bodyBuilder.HtmlBody = @"<p>Hi! Please find attached your purchase list. Thanks! :)</p>
                                    <table >
                                    <thead>
                                    <tr>
                                    <th> Product Name </th>
                                    <th> Price </th>                
                                    <th> Quantity </th>                 
                                    <th> Sub-Total </th>                
                                    <th> Purchase Date </th >
                                    </tr>                
                                    <thead>
                                    <tbody> " + bodyBuilder.HtmlBody +
                                    @"<tbody>
                                    </table> ";                





            message.Body = new TextPart(TextFormat.Html) { Text = bodyBuilder.HtmlBody };

            using var smtpClient = new SmtpClient();
            smtpClient.Connect("smtp.ethereal.email", 587, SecureSocketOptions.StartTls);
            smtpClient.Authenticate("dangelo19@ethereal.email", "yxP5MZ9aZKzCJp5JZE");
            smtpClient.Send(message);
            smtpClient.Disconnect(true);


            cart.Clear();
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Product");
        }

    }
}

eCommWeb/Controllers/HistoryController.cs
using eCommWeb.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace eCommWeb.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ApplicationDbContext _context;


        public HistoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Get()
        {
            //var query = _context.Item.Where(c => c.IdentityUserName == HttpContext.User.Identity.Name).ToList();

            //var query =  _context.Item.Include("Product").Where(c => c.IdentityUserName == HttpContext.User.Identity.Name)

        var query = from d in _context.Item
                      .Include(x => x.Product)
                      .Where(d => d.IdentityUserName == HttpContext.User.Identity.Name)
        select new { d.Product.Name, d.Product.Photo, d.Product.Price, d.Quantity, d.SubTotal, d.PurchaseDate, d.IdentityUserName };


            //Select new { product.Name, product.Photo, product.Price, item.Quantity, item.SubTotal, item.PurchaseDate, item.IdentityUserName };

            //var query = from item in _context.Item
            //            join product in _context.Product on item.Id equals product.Id
            //            //join patient in _context.Patient on doctor.Id equals patient.DoctorId
            //            where .Id.cont
            //            select new { product.Name, product.Photo, product.Price, item.Quantity, item.SubTotal, item.PurchaseDate, item.IdentityUserName };


            return Json(new { data = query });
        }






    }
}

eCommWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eComm</title>
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eCommWeb.styles.css" asp-append-version="true" />*@


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/bootswatch_zyphyr.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />



</head>
<body>
    <header>
@*        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eCommWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">eComm</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="History" asp-action="Index">History</a>
            @*<a class="nav-link text-white" href="History/Index" role="button" aria-haspopup="true" aria-expanded="false">Purchase History</a>*@

           @* <a class="nav-link text-white" asp-area="" asp-page="/History/Index">Doctor Patient</a>*@
        </li>

@*        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>*@
        @*<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <partial name="_LoginPartial" />
@*      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>



    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eCommWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@


    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>